### ISSUE TITLE
Explorar una estrategia de caché

### ISSUE THREAD

**Issue by eldisgustin** [raicerk/webscrapping#2]

**Comment by raicerk** [comment]
Se crean dos propuestas, ramas de features/estrategia-cache-....

**Comment by agonzalezmurua** [comment]
https://github.com/raicerk/webscrapping/tree/feature/estrategia-cache-memcache-api

**Comment by eldisgustin** [comment]
Esta es mi propuesta: [Estrategia memory-cache](https://github.com/raicerk/webscrapping/tree/feature/estrategia-cache-memcache-api)

Consiste en agregar `memory-cache` con duración limitada en base al recurso solicitado y responder con cabeceras `Control-Cache`

**Comment by raicerk** [comment]
Esta es mi propuesta: [Estrategia memory-cache](https://github.com/raicerk/webscrapping/tree/feature/estrategia-cache-memcache-scrapping)

**Comment by eldisgustin** [comment]
Resuelto en https://github.com/raicerk/webscrapping/pull/3
